inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/integration/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/annotate.rb'

Style/FetchEnvVar:
  Exclude:
    - 'lib/annotate/helpers.rb'
