name: CI
on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        gemfile:
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_1.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: latest
          bundler-cache: true

      - name: Run Tests
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler: latest
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop
